language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
env:
  - CC=gcc-4.8 CXX=g++-4.8
install:
  # install a newer version of CMake:
  - sudo apt-get remove -y cmake
  - curl -fsSL http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh > /tmp/install-cmake.sh
  - chmod +x /tmp/install-cmake.sh
  - sudo /tmp/install-cmake.sh --prefix=/usr/local --exclude-subdir
  - pip install .
  # install Ninja
  - sudo apt-get install ninja-build
before_script:
  - /bin/bash .travis_init.sh
# command to run tests
script: python setup.py test 
